### ISSUE TITLE
关于水印设置功能的问题

### ISSUE THREAD

**Issue by monstarw** [itorr/90s-time-machine#1]
在水印设置中，“_显示蒸汽机水印_”和“_显示预设名_”两项都勾选上时，调节“_盖印比例_”会同时影响水印和预设名的显示大小。但是如果不勾选“_显示蒸汽机水印_”而只勾选“_显示预设名_”时，下方的四个设置项均处于不可用状态。既然可以调整预设名的显示大小，考虑把水印和预设名的设置分开？比如把“_显示蒸汽机水印_”和“_显示预设名_”两个复选框改为二选一的单选框，便于单独设置水印和预设名。

第一次在github上提issue，如有疏漏请多包涵！

**Comment by itorr** [comment]
感谢 issue ，确实值得分开了，细节要考虑考虑🤔

**Comment by itorr** [comment]
https://github.com/itorr/vaporwave/commit/6d3378ea227e51673dd369bc7743a02f0e140eed
预设名部分选项独立了w
